import os
import multiprocessing
import ctypes
import sys
import winreg
import subprocess
import datetime
import json
from pathlib import Path

try:
    from colorama import init, Fore, Style
    init(autoreset=True)
    HAS_COLOR = True
except ImportError:
    HAS_COLOR = False
    class Fore:
        GREEN = CYAN = YELLOW = RED = WHITE = MAGENTA = ""
    class Style:
        BRIGHT = RESET_ALL = ""

LOG_FILE = "optimizer_log.txt"
MAX_LOG_SIZE = 1 * 1024 * 1024

def rotate_log():
    if os.path.exists(LOG_FILE) and os.path.getsize(LOG_FILE) > MAX_LOG_SIZE:
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        backup = f"{LOG_FILE}.{timestamp}.bak"
        try:
            os.rename(LOG_FILE, backup)
        except:
            pass

def log(message: str):
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(f"[{timestamp}] {message}\n")

def cprint(text, color="", bright=False):
    prefix = (Style.BRIGHT if bright else "") + color if HAS_COLOR else ""
    print(f"{prefix}{text}{Style.RESET_ALL if HAS_COLOR else ''}")

def is_admin():
    try:
        return ctypes.windll.shell32.IsUserAnAdmin()
    except:
        return False

def get_folder_size_mb(path: str) -> float:
    if not os.path.exists(path):
        return 0.0
    total = 0
    try:
        for dirpath, _, filenames in os.walk(path):
            for f in filenames:
                fp = os.path.join(dirpath, f)
                try:
                    total += os.path.getsize(fp)
                except:
                    pass
    except:
        pass
    return round(total / (1024 * 1024), 2)

def get_steam_path() -> str:
    try:
        key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, r"Software\Valve\Steam")
        steam_path, _ = winreg.QueryValueEx(key, "SteamPath")
        winreg.CloseKey(key)
        return os.path.normpath(steam_path)
    except:
        return None

def flush_dns(txt):
    cprint(txt["dns_flush"], Fore.CYAN)
    try:
        result = subprocess.run(["ipconfig", "/flushdns"], capture_output=True, text=True)
        if result.returncode == 0:
            cprint(txt["dns_ok"], Fore.GREEN)
            log("DNS cache flushed successfully")
        else:
            cprint(txt["dns_fail"], Fore.YELLOW)
            log(f"DNS flush failed: {result.stderr.strip()}")
    except Exception as e:
        cprint(f"{txt['dns_fail']}: {e}", Fore.YELLOW)
        log(f"DNS flush error: {e}")

def set_high_performance_power_plan(txt):
    cprint(txt["power_plan"], Fore.CYAN)
    try:
        result = subprocess.run(
            ["powercfg", "/setactive", "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            cprint(txt["power_ok"], Fore.GREEN)
            log("Power plan set to High Performance")
        else:
            cprint(txt["power_fail"], Fore.YELLOW)
            log(f"Power plan set failed: {result.stderr.strip()}")
    except Exception as e:
        cprint(f"{txt['power_fail']}: {e}", Fore.YELLOW)
        log(f"Power plan error: {e}")

def disable_xbox_gamebar(txt):
    cprint(txt["gamebar"], Fore.CYAN)
    try:
        keys = [
            (winreg.HKEY_CURRENT_USER, r"SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR", "AppCaptureEnabled", 0),
            (winreg.HKEY_CURRENT_USER, r"System\GameConfigStore", "GameDVR_Enabled", 0),
        ]
        for hive, path, name, value in keys:
            try:
                key = winreg.OpenKey(hive, path, 0, winreg.KEY_SET_VALUE)
                winreg.SetValueEx(key, name, 0, winreg.REG_DWORD, value)
                winreg.CloseKey(key)
            except:
                pass
        cprint(txt["gamebar_ok"], Fore.GREEN)
        log("Xbox GameBar/DVR disabled")
    except Exception as e:
        cprint(f"{txt['gamebar_fail']}: {e}", Fore.YELLOW)
        log(f"GameBar disable error: {e}")

def set_cs2_priority(txt):
    cprint(txt["priority"], Fore.CYAN)
    try:
        script = (
            "Get-Process cs2 -ErrorAction SilentlyContinue | "
            "ForEach-Object { $_.PriorityClass = 'High' }"
        )
        subprocess.Popen(
            ["powershell", "-Command", script],
            creationflags=subprocess.CREATE_NO_WINDOW
        )
        cprint(txt["priority_ok"], Fore.GREEN)
        log("CS2 process priority set to High")
    except Exception as e:
        cprint(f"{txt['priority_fail']}: {e}", Fore.YELLOW)
        log(f"Priority set error: {e}")

def generate_autoexec(cs2_path: str, txt):
    cprint(txt["autoexec"], Fore.CYAN)
    try:
        cfg_dir = os.path.join(cs2_path, "game", "csgo", "cfg")
        os.makedirs(cfg_dir, exist_ok=True)
        autoexec_path = os.path.join(cfg_dir, "autoexec.cfg")
        content = (
            "// Generated by CS2 Hybrid Optimizer\n"
            "fps_max 0\n"
            "fps_max_ui 60\n"
            "cl_interp 0\n"
            "cl_interp_ratio 1\n"
            "cl_updaterate 128\n"
            "cl_cmdrate 128\n"
            "rate 786432\n"
            "mm_dedicated_search_maxping 50\n"
            "net_client_steamdatagram_enable_override 1\n"
            "voice_enable 1\n"
            "voice_scale 0.4\n"
        )
        with open(autoexec_path, "w") as f:
            f.write(content)
        cprint(txt["autoexec_ok"], Fore.GREEN)
        log(f"autoexec.cfg generated at {autoexec_path}")
    except Exception as e:
        cprint(f"{txt['autoexec_fail']}: {e}", Fore.YELLOW)
        log(f"autoexec generation error: {e}")

def add_defender_exclusion(path: str, txt):
    cprint(txt["defender"], Fore.CYAN)
    try:
        subprocess.run(
            ["powershell", "-Command", f"Add-MpPreference -ExclusionPath '{path}'"],
            capture_output=True,
            creationflags=subprocess.CREATE_NO_WINDOW
        )
        cprint(f"{txt['defender_ok']}: {path}", Fore.GREEN)
        log(f"Defender exclusion added: {path}")
    except Exception as e:
        cprint(f"{txt['defender_fail']}: {e}", Fore.YELLOW)
        log(f"Defender exclusion error: {e}")

def set_win32_priority_separation(txt):
    cprint(txt["priority_sep"], Fore.CYAN)
    try:
        key = winreg.OpenKey(
            winreg.HKEY_LOCAL_MACHINE,
            r"SYSTEM\CurrentControlSet\Control\PriorityControl",
            0, winreg.KEY_SET_VALUE
        )
        winreg.SetValueEx(key, "Win32PrioritySeparation", 0, winreg.REG_DWORD, 0x26)
        winreg.CloseKey(key)
        cprint(txt["priority_sep_ok"], Fore.GREEN)
        log("Win32PrioritySeparation set to 0x26 (foreground-favoring)")
    except Exception as e:
        cprint(f"{txt['priority_sep_fail']}: {e}", Fore.YELLOW)
        log(f"Win32PrioritySeparation error: {e}")

def set_system_responsiveness(txt):
    cprint(txt["sys_resp"], Fore.CYAN)
    try:
        key = winreg.OpenKey(
            winreg.HKEY_LOCAL_MACHINE,
            r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile",
            0, winreg.KEY_SET_VALUE
        )
        winreg.SetValueEx(key, "SystemResponsiveness", 0, winreg.REG_DWORD, 0)
        winreg.CloseKey(key)
        cprint(txt["sys_resp_ok"], Fore.GREEN)
        log("SystemResponsiveness set to 0")
    except Exception as e:
        cprint(f"{txt['sys_resp_fail']}: {e}", Fore.YELLOW)
        log(f"SystemResponsiveness error: {e}")

def disable_fullscreen_optimizations(cs2_path: str, txt):
    cprint(txt["fse"], Fore.CYAN)
    try:
        exe_path = os.path.join(cs2_path, "game", "bin", "win64", "cs2.exe")
        if not os.path.exists(exe_path):
            cprint(txt["fse_fail"], Fore.YELLOW)
            return
        key = winreg.OpenKey(
            winreg.HKEY_CURRENT_USER,
            r"Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers",
            0, winreg.KEY_SET_VALUE
        )
        winreg.SetValueEx(key, exe_path, 0, winreg.REG_SZ, "~ DISABLEDXMAXIMIZEDWINDOWEDMODE")
        winreg.CloseKey(key)
        cprint(txt["fse_ok"], Fore.GREEN)
        log(f"Fullscreen optimizations disabled for {exe_path}")
    except Exception as e:
        cprint(f"{txt['fse_fail']}: {e}", Fore.YELLOW)
        log(f"Fullscreen optimization disable error: {e}")

def main():
    rotate_log()

    strings_db = {
        "en": {
            "title":         "CS2 HYBRID OPTIMIZER v2.0  |  Python + C",
            "launch":        "GENERATED LAUNCH OPTIONS:",
            "checking":      "[ .. ] Closing background CS2 processes...",
            "call_c_gpu":    "[ .. ] C-Engine: Clearing GPU shader cache...",
            "call_c_steam":  "[ .. ] C-Engine: Clearing Steam shader cache (AppID 730)...",
            "call_c_ram":    "[ .. ] C-Engine: Purging RAM Standby List...",
            "success":       "[ OK ] C-Engine finished. System is clean.",
            "launching":     "[ >> ] Launching Counter-Strike 2...",
            "ask_launch":    "Launch Counter-Strike 2 now? (Y/N): ",
            "exit":          "Press Enter to exit...",
            "freed":         "[ MB ] Freed",
            "dns_flush":     "[ .. ] Flushing DNS cache...",
            "dns_ok":        "[ OK ] DNS cache flushed.",
            "dns_fail":      "[ !! ] DNS flush failed (non-critical).",
            "power_plan":    "[ .. ] Switching to High Performance power plan...",
            "power_ok":      "[ OK ] High Performance power plan activated.",
            "power_fail":    "[ !! ] Could not switch power plan.",
            "gamebar":       "[ .. ] Disabling Xbox GameBar / GameDVR...",
            "gamebar_ok":    "[ OK ] Xbox GameBar disabled.",
            "gamebar_fail":  "[ !! ] Could not disable GameBar.",
            "priority":      "[ .. ] Setting CS2 process priority to High...",
            "priority_ok":   "[ OK ] CS2 priority set to High.",
            "priority_fail": "[ !! ] Could not set priority.",
            "autoexec":      "[ .. ] Generating autoexec.cfg...",
            "autoexec_ok":   "[ OK ] autoexec.cfg created.",
            "autoexec_fail": "[ !! ] Could not create autoexec.cfg.",
            "summary":       "SUMMARY",
            "log_saved":     "Log saved to",
            "dll_error":     "[ !! ] DLL Error",
            "call_c_timer":  "[ .. ] C-Engine: Requesting high-precision system timer...",
            "defender":      "[ .. ] Adding CS2 folder to Defender exclusions...",
            "defender_ok":   "[ OK ] Defender exclusion added",
            "defender_fail": "[ !! ] Could not add Defender exclusion",
            "priority_sep":      "[ .. ] Tuning Win32PrioritySeparation for foreground boost...",
            "priority_sep_ok":   "[ OK ] Win32PrioritySeparation tuned.",
            "priority_sep_fail": "[ !! ] Could not tune Win32PrioritySeparation.",
            "sys_resp":      "[ .. ] Disabling MMCSS background task throttling...",
            "sys_resp_ok":   "[ OK ] SystemResponsiveness set to 0.",
            "sys_resp_fail": "[ !! ] Could not set SystemResponsiveness.",
            "fse":           "[ .. ] Disabling Fullscreen Optimizations for cs2.exe...",
            "fse_ok":        "[ OK ] Fullscreen Optimizations disabled for CS2.",
            "fse_fail":      "[ !! ] Could not disable Fullscreen Optimizations.",
        },
        "ru": {
            "title":         "ГИБРИДНЫЙ ОПТИМИЗАТОР CS2 v2.0  |  Python + C",
            "launch":        "СФОРМИРОВАННЫЕ ПАРАМЕТРЫ ЗАПУСКА:",
            "checking":      "[ .. ] Закрываю фоновые процессы CS2...",
            "call_c_gpu":    "[ .. ] Си-Мотор: Очищаю кэш шейдеров GPU...",
            "call_c_steam":  "[ .. ] Си-Мотор: Очищаю кэш шейдеров Steam (AppID 730)...",
            "call_c_ram":    "[ .. ] Си-Мотор: Сброс Standby List ОЗУ...",
            "success":       "[ OK ] Си-Мотор завершил работу. Система чиста.",
            "launching":     "[ >> ] Запускаю Counter-Strike 2...",
            "ask_launch":    "Запустить Counter-Strike 2 сейчас? (Y/N): ",
            "exit":          "Нажмите Enter для выхода...",
            "freed":         "[ MB ] Освобождено",
            "dns_flush":     "[ .. ] Очищаю DNS-кэш...",
            "dns_ok":        "[ OK ] DNS-кэш очищен.",
            "dns_fail":      "[ !! ] Не удалось очистить DNS (не критично).",
            "power_plan":    "[ .. ] Переключаю план питания на Высокую производительность...",
            "power_ok":      "[ OK ] Активирован план: Высокая производительность.",
            "power_fail":    "[ !! ] Не удалось переключить план питания.",
            "gamebar":       "[ .. ] Отключаю Xbox GameBar / GameDVR...",
            "gamebar_ok":    "[ OK ] Xbox GameBar отключён.",
            "gamebar_fail":  "[ !! ] Не удалось отключить GameBar.",
            "priority":      "[ .. ] Повышаю приоритет процесса CS2...",
            "priority_ok":   "[ OK ] Приоритет CS2 установлен на Высокий.",
            "priority_fail": "[ !! ] Не удалось установить приоритет.",
            "autoexec":      "[ .. ] Генерирую autoexec.cfg...",
            "autoexec_ok":   "[ OK ] autoexec.cfg создан.",
            "autoexec_fail": "[ !! ] Не удалось создать autoexec.cfg.",
            "summary":       "ИТОГ",
            "log_saved":     "Лог сохранён в",
            "dll_error":     "[ !! ] Ошибка DLL",
            "call_c_timer":  "[ .. ] Си-Мотор: Запрашиваю точный системный таймер...",
            "defender":      "[ .. ] Добавляю папку CS2 в исключения Defender...",
            "defender_ok":   "[ OK ] Исключение Defender добавлено",
            "defender_fail": "[ !! ] Не удалось добавить исключение Defender",
            "priority_sep":      "[ .. ] Настраиваю Win32PrioritySeparation для приоритета активного окна...",
            "priority_sep_ok":   "[ OK ] Win32PrioritySeparation настроен.",
            "priority_sep_fail": "[ !! ] Не удалось настроить Win32PrioritySeparation.",
            "sys_resp":      "[ .. ] Отключаю троттлинг фоновых задач (MMCSS)...",
            "sys_resp_ok":   "[ OK ] SystemResponsiveness установлен в 0.",
            "sys_resp_fail": "[ !! ] Не удалось установить SystemResponsiveness.",
            "fse":           "[ .. ] Отключаю Fullscreen Optimizations для cs2.exe...",
            "fse_ok":        "[ OK ] Fullscreen Optimizations отключены для CS2.",
            "fse_fail":      "[ !! ] Не удалось отключить Fullscreen Optimizations.",
        }
    }

    lang = "ru"
    for arg in sys.argv:
        if arg.startswith("--lang="):
            lang = arg.split("=")[1]

    if not is_admin() and not any(arg.startswith("--lang=") for arg in sys.argv):
        os.system('cls')
        print("=" * 60)
        print("  Select language / Выберите язык:")
        print("=" * 60)
        print("  1 - English")
        print("  2 - Русский")
        print("=" * 60)
        choice = input("👉 ").strip()
        lang = "en" if choice == "1" else "ru"

    if not is_admin():
        if getattr(sys, 'frozen', False):
            arg_list = sys.argv[1:]
        else:
            arg_list = sys.argv
        args = [f'"{arg}"' for arg in arg_list] + [f"--lang={lang}"]
        ctypes.windll.shell32.ShellExecuteW(None, "runas", sys.executable, " ".join(args), None, 1)
        sys.exit(0)

    txt = strings_db.get(lang, strings_db["ru"])
    os.system('cls')

    log("=" * 50)
    log(f"Optimizer started | lang={lang}")

    cprint("=" * 62, Fore.CYAN, bright=True)
    cprint(f"  {txt['title']}", Fore.CYAN, bright=True)
    cprint("=" * 62, Fore.CYAN, bright=True)

    cores = multiprocessing.cpu_count()
    threads_for_cs2 = cores // 2 if cores > 4 else cores
    launch_options = f"-high -nojoy -fullscreen -threads {threads_for_cs2} +fps_max 0 +exec autoexec"

    cprint(f"\n  {txt['launch']}", Fore.YELLOW, bright=True)
    cprint(f"  {launch_options}\n", Fore.GREEN, bright=True)
    log(f"Launch options: {launch_options}")
    cprint("-" * 62, Fore.WHITE)

    steam_path = get_steam_path()
    cs2_path = None
    if steam_path:
        candidate = os.path.normpath(f"{steam_path}/steamapps/common/Counter-Strike 2")
        if os.path.exists(candidate):
            cs2_path = candidate
            add_defender_exclusion(cs2_path, txt)

    cprint(txt["checking"], Fore.CYAN)
    try:
        subprocess.run(["taskkill", "/f", "/im", "cs2.exe"], capture_output=True, creationflags=subprocess.CREATE_NO_WINDOW)
    except:
        pass

    if getattr(sys, 'frozen', False):
        base_path = sys._MEIPASS
    else:
        base_path = os.path.dirname(__file__)

    freed_total = 0.0
    localappdata = os.environ.get("LOCALAPPDATA", "")

    cache_paths = {
        "D3DSCache":    os.path.join(localappdata, "D3DSCache"),
        "NVIDIA DXCache": os.path.join(localappdata, "NVIDIA", "DXCache"),
        "NVIDIA GLCache": os.path.join(localappdata, "NVIDIA", "GLCache"),
        "AMD DxCache":  os.path.join(localappdata, "AMD", "DxCache"),
        "AMD OglCache": os.path.join(localappdata, "AMD", "OglCache"),
        "AMD VkCache":  os.path.join(localappdata, "AMD", "VkCache"),
    }
    if steam_path:
        steam_shader = os.path.join(steam_path, "shadercache", "730")
        cache_paths["Steam Shader 730"] = steam_shader

    for name, path in cache_paths.items():
        mb = get_folder_size_mb(path)
        freed_total += mb
        if mb > 0:
            log(f"Cache [{name}] before cleanup: {mb} MB")

    try:
        dll_path = os.path.join(base_path, 'cleaner.dll')
        c_library = ctypes.CDLL(dll_path)

        cprint(txt["call_c_gpu"], Fore.CYAN)
        gpu_ok = c_library.clear_gpu_cache()
        log(f"GPU cache cleanup returned: {gpu_ok}")

        cprint(txt["call_c_steam"], Fore.CYAN)
        c_library.clear_steam_shader_cache_ex.argtypes = [ctypes.c_char_p]
        steam_shader_path = (steam_path or "").encode("utf-8") if steam_path else b""
        steam_ok = c_library.clear_steam_shader_cache_ex(steam_shader_path)
        log(f"Steam shader cache cleanup returned: {steam_ok}")

        cprint(txt["call_c_ram"], Fore.CYAN)
        ram_ok = c_library.clear_ram_standby_list()
        log(f"RAM standby list cleanup returned: {ram_ok}")

        cprint(txt["call_c_timer"], Fore.CYAN)
        timer_ok = c_library.force_high_precision_timer()
        log(f"High-precision timer request returned: {timer_ok}")

        cprint(f"\n{txt['success']}", Fore.GREEN, bright=True)
        log("C-engine finished successfully")

    except Exception as e:
        cprint(f"\n{txt['dll_error']}: {e}", Fore.RED)
        log(f"DLL error: {e}")

    cprint("-" * 62, Fore.WHITE)

    flush_dns(txt)
    set_high_performance_power_plan(txt)
    disable_xbox_gamebar(txt)
    set_win32_priority_separation(txt)
    set_system_responsiveness(txt)
    if cs2_path:
        generate_autoexec(cs2_path, txt)
        disable_fullscreen_optimizations(cs2_path, txt)

    cprint("-" * 62, Fore.WHITE)

    cprint(f"\n  ══ {txt['summary']} ══", Fore.MAGENTA, bright=True)
    cprint(f"  {txt['freed']}: {freed_total:.1f} MB", Fore.GREEN, bright=True)
    cprint(f"  {txt['log_saved']}: {LOG_FILE}", Fore.YELLOW)
    log(f"Total freed (estimated): {freed_total:.1f} MB")
    log("=" * 50)

    cprint("=" * 62, Fore.CYAN, bright=True)

    ask = input(f"\n  {txt['ask_launch']}").strip().lower()
    if ask in ['y', 'yes', 'д', 'да', '']:
        cprint(txt["launching"], Fore.GREEN, bright=True)
        try:
            subprocess.Popen(f'start steam://run/730// {launch_options}', shell=True)
        except:
            os.system(f'start steam://run/730// {launch_options}')
        import threading
        threading.Timer(5.0, set_cs2_priority, args=[txt]).start()

    print()
    input(f"  {txt['exit']}")

if __name__ == "__main__":
    main()